version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db-postgres
    environment:
      POSTGRES_DB: avaliacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - rede-app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/avaliacao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - rede-app

networks:
  rede-app:
